### ISSUE TITLE
don't include challenge and exercise titles in outline

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/varnish#2]
This is minor and will probably be easily handled by the UI developer, but I don't think that the titles of the challenges and the word "solution" should be included in the outline that appears in the right column in the lessons.

![Screenshot from 2021-01-27 09-09-09](https://user-images.githubusercontent.com/5502922/105961840-0d7d5d00-604d-11eb-9f8d-c85d88f26d9f.png)

**Comment by zkamvar** [comment]
This is happening because the navbar is scanning all of the headers without respect to document sections (divs) and displaying the largest two header levels.

I think part of the solution (ha!) will be to enforce proper heading layout in the lessons something like:

```
- Episode Title (h1)
  | - Section (h2)
     | - Challenge (h3)
        | - Solution (h4)
     | - Callout (h3)
  | - Section (h2)
``` 

Note that we don't do this at the moment in the current template as python-novice-inflammation uses level-3 headings throughout.

**Comment by fmichonneau** [comment]
yes, that'd be an improvement. I think to remember there is an additional class/setting that can be added to tell the TOC generator to ignore some titles.

**Comment by zkamvar** [comment]
This should be a non-issue for the new frontend
