### ISSUE TITLE
Change ToC Headline to Episodes

### ISSUE THREAD

**Issue by fiveop** [carpentries/varnish#26]
The table of contents has “Chapters” as its headline. Other than the first (”Summary and Setup/Schedule”) the items list episodes, so the headline should probably read ”Episodes”. (I qualify with “probably” because the first item is NOT and episode. Maybe “Table of Contents” is even better than “Episodes” or “Chapters”.)

I noticed this showing material to someone unfamiliar with the Carpentries getting confused about the terms lesson, episode, and chapter.

**Comment by zkamvar** [comment]
This is a bit of a work in progress. The confusion about the term "Episode" was noted in the [design phase of the front-end][1], which is why we changed have the term "Chapters" at the top. It's something that we will work on transitioning after we run our [beta testing]

[1]: https://carpentries.org/blog/2021/05/lesson-template-design-process/
[beta testing]: https://carpentries.org/blog/2022/01/live-lesson-infrastructure/

**Comment by fiveop** [comment]
It seems that you went with “Episodes” now, so this issue can be closed.
