### ISSUE TITLE
Visual layout on large monitors

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/varnish#35]
On a large monitor (27" diagnoal; 2560x1440 resolution) the sidebar & overall menu behavior feels unintentional

It  would have had plenty of space to not shrink the text and open the sidebar without moving but it shrinks it anyway. 
collapsed
![sandpaper-wide](https://user-images.githubusercontent.com/10656079/167701069-fc4188a5-8886-4da6-9b2a-7c0f59de4be6.png)

expanded:
![sandpaper_menu_error](https://user-images.githubusercontent.com/10656079/167700488-67857958-31e9-4853-bdc7-72f7c122666a.png)

expanded there is also a problem with the the top menu bar. It does not pull items out of the dropdown which could be okay, but then if there are too many of them in the drop down, they end up behind the sidebar (and unreadable)

**Comment by zkamvar** [comment]
Thank you for the report! You'll have to be patient with me as my CSS skills are not well refined. 

## Dropdown menu issue

I believe the dropdown issue can be fixed by adjusting the z-index of the dropdown menus to be 3 or higher since the current z-index of the sidebar is 2:

https://github.com/carpentries/varnish/blob/1333c27055bdba512101fa31f10e972f0a068b74/source/stylesheets/sidenav.scss#L1-L11

## Sidebar with room

I believe we might be able to define an XXL media breakpoint (https://getbootstrap.com/docs/5.0/layout/breakpoints/). I'm not sure why we don't have it. I suspect this was a "be careful what you wish for" kind of situation in communicating with the designers. 

Nevertheless, this particular one will take a little bit more thought and testing than the previous.

**Comment by brownsarahm** [comment]
thanks! 

the one that will take a bit more thought & testing is less urgent too.  let me know if I can help test again.

**Comment by ErinBecker** [comment]
Fixed with https://github.com/carpentries/varnish/pull/36
