### ISSUE TITLE
Ordered lists do not render correctly in `solution` box

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/varnish#51]
```Markdown
::: challenge

1. Monday
1. Tuesday
1. Wednesday
1. Thursday
1. Friday

:::::: solution

1. Saturday
1. Sunday

::::::

:::
```

becomes in the built page:

![Screenshot of a challenge and solution block on an episode page, with the days of the week Monday through Friday appearing as a numbered list in the challenge body, and Saturday and Sunday listed without item markers in the solution body.](https://user-images.githubusercontent.com/9694524/179211582-cfdde650-910c-4837-888c-a323ae86b8c2.png)

**Comment by zkamvar** [comment]
This is coming from 

https://github.com/carpentries/varnish/blob/79b523d546544dc94ee5d4430224a1e2043a2100/source/stylesheets/sidenav.scss#L130-L132

because the solution has the `.accordion-body` class, which is also used for the side navigation menus. It's also worth mentioning that fixing this will make sure that list items are displayed correctly in instructor notes.

**Comment by zkamvar** [comment]
It should be fixed and will be available on the universe in about an hour or less
