### ISSUE TITLE
callout blocks that span multiple lines have double underline

### ISSUE THREAD

**Issue by anenadic** [carpentries/varnish#53]
As shown in the image below:

![screenshot of a callout block with the title "Exercise: prioritising issues & sprint planning (15 min)" showing a doubled underline](https://user-images.githubusercontent.com/631719/181015468-d566906e-cbf4-4be2-b155-9c2f6b8e48b7.png)

I suspect this is not specific to exercise blocks.

**Comment by zkamvar** [comment]
Thank you for reporting this! I've been meaning to open an issue for it, but never got around to it.

## Source and Potential Solution

The styling of this element is controlled here on lines 34 and 35:

https://github.com/carpentries/varnish/blob/f2df91f5ecd8e06117f2e802278b4138bb2c743c/source/stylesheets/callouts.scss#L26-L36

There are _several_ potential solutions to this problem in https://css-tricks.com/styling-underlines-web/


## Origin

For posterity (and for anyone who wants to avoid the mistakes we made): this issue arose because when we were designing the headings for this, we tested a lesson that had short headings and did not realise that it would be a problem.
